import Head from 'next/head';
import Work from '../../components/works/work';

export default function Works() {
  return (
    <div>
      <Head>
        <title>NextJS Works</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='px-6'>
        <div className='max-w-4xl mx-auto'>
          <h1 className='text-3xl font-bold mb-6'>Works</h1>
          <Work />
          <Work />
          <Work />
          <Work />
        </div>
      </section>
    </div>
  );
}