import Head from 'next/head';
import Work from '../../components/works/work';
import { getAllWork, WorkType } from '../lib/api';

export async function getStaticProps() {
  const works = getAllWork();

  return {
    props: {
      works,
    },
  };
}
export default function Works({ works }: { works: WorkType[] }) {
  return (
    <div>
      <Head>
        <title>NextJS Works</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='px-6'>
        <div className='max-w-4xl mx-auto'>
          <h1 className='text-3xl font-bold mb-6'>Works</h1>
          {works.map((workItem) => (
            <Work key={workItem.title} item={workItem} />
          ))};
        </div>
      </section>
    </div>
  );
}