import Head from 'next/head';

// @ts-ignore
import { Progress } from 'react-sweet-progress';
import "react-sweet-progress/lib/style.css";

import { getAllSkill, Skill } from '@/lib/api';

export default function Skills({ skills }: { skills: Skill[] }) {
  return (
    <div>
      <Head>
        <title>NextJS Skill</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='px-6'>
        <div className='max-w-4xl mx-auto'>
          <div className='p-3 border bg-indigo-500 rounded-md shadow-md mb-4'>
            <h1 className='text-3xl font-bold text-yellow-200'>My Skills</h1>
          </div>
          {
            skills.map((skill, i) => (
              <div key={i} className='flex flex-row justify-between items-center'>
                <div className='w-[200px]'>
                  <h3 className='text-xl font-semibold'>{skill.title}</h3>
                </div>
                <Progress theme={{
                  success: {
                    symbol: '😁',
                    color: 'rgb(15, 228, 180)'
                  },
                  error: {
                    symbol: '🧐',
                    color: 'rgb(250, 220, 220)'
                  },
                  active: {
                    symbol: '🥺',
                    color: 'rgb(230, 240, 25)'
                  },
                }} percent={skill.percent} status={skill.status} />
              </div>
            ))
          }
        </div>
      </section>
    </div>
  );
}

export async function getStaticProps() {
  const skills = getAllSkill();

  return {
    props: {
      skills,
    },
  };
}