import Head from 'next/head'
import IntroHeader from "../components/introduction";
import FeaturedSkill from '@/components/skills';
import FeaturedWork from "../components/works/works";
import { getAllWork, WorkType, Skill, getAllSkill } from '../lib/api';

interface Post {
  slug: string
  [key: string]: string
}

interface Props {
  skills: Skill[]
  works: WorkType[]
}

export default function Home({ skills, works }: Props) {
  return (
    <div>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IntroHeader />
      <FeaturedSkill skills={skills} />
      <FeaturedWork works={works} />
    </div>
  )
}

export async function getStaticProps() {
  const skills = getAllSkill();
  const works = getAllWork();

  return {
    props: {
      skills,
      works
    },
  };
}