import Head from 'next/head'
import IntroHeader from "../components/introduction";
import RecentPosts from "../components/posts/posts";
import FeaturedWork from "../components/works/works";
import { getAllPosts, getAllWork, WorkType } from './lib/api';

interface Post {
  slug: string
  [key: string]: string
}

interface Props {
  posts: Post[]
  works: WorkType[]
}

export default function Home({ posts, works }: Props) {
  return (
    <div>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IntroHeader />
      <RecentPosts posts={posts} />
      <FeaturedWork works={works} />
    </div>
  )
}

export async function getStaticProps() {
  const posts = getAllPosts();
  const works = getAllWork();

  return {
    props: {
      posts,
      works
    },
  };
}