import Head from 'next/head';

import Post from '../../components/posts/post';
import { getAllPosts } from '../lib/api';

interface Post {
  slug: string
  [key: string]: string
}

export default function Blogs({ posts }: { posts: Post[] }) {
  return (
    <div>
      <Head>
        <title>NextJS Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='px-6'>
        <div className='max-w-4xl mx-auto'>
          <h1 className='text-3xl font-bold mb-6'>Blog</h1>
          {
            posts.map((post) => (
              <Post key={post.slug} className='border-b-2' post={post} />
            ))
          }
        </div>
      </section>
    </div>
  );
}

export async function getStaticProps() {
  const posts = getAllPosts();

  return {
    props: {
      posts,
    },
  };
}