import Head from 'next/head';

import fs from 'fs'
import matter from "gray-matter";

import Post from '../../components/posts/post';

interface Post {
  slug: string
  [key: string]: string
}

export default function Blogs({ posts }: { posts: Post[] }) {
  console.log(posts)
  return (
    <div>
      <Head>
        <title>NextJS Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='px-6'>
        <div className='max-w-4xl mx-auto'>
          <h1 className='text-3xl font-bold mb-6'>Blog</h1>
          {
            posts.map((post) => (
              <Post key={post.slug} className='border-b-2' post={post} />
            ))
          }
        </div>
      </section>
    </div>
  );
}

export async function getStaticProps() {
  const files = fs.readdirSync('./posts');

  const posts = files.map((fileName) => {
    const slug = fileName.replace('.md', '');
    const readFile = fs.readFileSync(`./posts/${fileName}`, 'utf-8');
    const { data: frontmatter } = matter(readFile);
    return {
      slug,
      ...frontmatter,
    };
  });

  return {
    props: {
      posts,
    },
  };
}